/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as MediathequeRouteImport } from './routes/mediatheque'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as DonsRouteImport } from './routes/dons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsSlugRouteImport } from './routes/projets.$slug'
import { Route as MediathequeVideosRouteImport } from './routes/mediatheque.videos'
import { Route as AnnuaireOrganisationsRouteImport } from './routes/annuaire.organisations'
import { Route as AnnuaireEcolesSpecialiseesRouteImport } from './routes/annuaire.ecoles-specialisees'
import { Route as AnnuaireEcolesInclusivesRouteImport } from './routes/annuaire.ecoles-inclusives'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const MediathequeRoute = MediathequeRouteImport.update({
  id: '/mediatheque',
  path: '/mediatheque',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const DonsRoute = DonsRouteImport.update({
  id: '/dons',
  path: '/dons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetsRoute,
} as any)
const MediathequeVideosRoute = MediathequeVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => MediathequeRoute,
} as any)
const AnnuaireOrganisationsRoute = AnnuaireOrganisationsRouteImport.update({
  id: '/annuaire/organisations',
  path: '/annuaire/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireEcolesSpecialiseesRoute =
  AnnuaireEcolesSpecialiseesRouteImport.update({
    id: '/annuaire/ecoles-specialisees',
    path: '/annuaire/ecoles-specialisees',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnnuaireEcolesInclusivesRoute =
  AnnuaireEcolesInclusivesRouteImport.update({
    id: '/annuaire/ecoles-inclusives',
    path: '/annuaire/ecoles-inclusives',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dons': typeof DonsRoute
  '/historique': typeof HistoriqueRoute
  '/mediatheque': typeof MediathequeRouteWithChildren
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/annuaire/ecoles-inclusives': typeof AnnuaireEcolesInclusivesRoute
  '/annuaire/ecoles-specialisees': typeof AnnuaireEcolesSpecialiseesRoute
  '/annuaire/organisations': typeof AnnuaireOrganisationsRoute
  '/mediatheque/videos': typeof MediathequeVideosRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dons': typeof DonsRoute
  '/historique': typeof HistoriqueRoute
  '/mediatheque': typeof MediathequeRouteWithChildren
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/annuaire/ecoles-inclusives': typeof AnnuaireEcolesInclusivesRoute
  '/annuaire/ecoles-specialisees': typeof AnnuaireEcolesSpecialiseesRoute
  '/annuaire/organisations': typeof AnnuaireOrganisationsRoute
  '/mediatheque/videos': typeof MediathequeVideosRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/admin': typeof AdminRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/dons': typeof DonsRoute
  '/historique': typeof HistoriqueRoute
  '/mediatheque': typeof MediathequeRouteWithChildren
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/annuaire/ecoles-inclusives': typeof AnnuaireEcolesInclusivesRoute
  '/annuaire/ecoles-specialisees': typeof AnnuaireEcolesSpecialiseesRoute
  '/annuaire/organisations': typeof AnnuaireOrganisationsRoute
  '/mediatheque/videos': typeof MediathequeVideosRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admin'
    | '/confidentialite'
    | '/contact'
    | '/dons'
    | '/historique'
    | '/mediatheque'
    | '/partenaires'
    | '/projets'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/annuaire/ecoles-inclusives'
    | '/annuaire/ecoles-specialisees'
    | '/annuaire/organisations'
    | '/mediatheque/videos'
    | '/projets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admin'
    | '/confidentialite'
    | '/contact'
    | '/dons'
    | '/historique'
    | '/mediatheque'
    | '/partenaires'
    | '/projets'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/annuaire/ecoles-inclusives'
    | '/annuaire/ecoles-specialisees'
    | '/annuaire/organisations'
    | '/mediatheque/videos'
    | '/projets/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admin'
    | '/confidentialite'
    | '/contact'
    | '/dons'
    | '/historique'
    | '/mediatheque'
    | '/partenaires'
    | '/projets'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/annuaire/ecoles-inclusives'
    | '/annuaire/ecoles-specialisees'
    | '/annuaire/organisations'
    | '/mediatheque/videos'
    | '/projets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AdminRoute: typeof AdminRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DonsRoute: typeof DonsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  MediathequeRoute: typeof MediathequeRouteWithChildren
  PartenairesRoute: typeof PartenairesRoute
  ProjetsRoute: typeof ProjetsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnnuaireEcolesInclusivesRoute: typeof AnnuaireEcolesInclusivesRoute
  AnnuaireEcolesSpecialiseesRoute: typeof AnnuaireEcolesSpecialiseesRoute
  AnnuaireOrganisationsRoute: typeof AnnuaireOrganisationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediatheque': {
      id: '/mediatheque'
      path: '/mediatheque'
      fullPath: '/mediatheque'
      preLoaderRoute: typeof MediathequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dons': {
      id: '/dons'
      path: '/dons'
      fullPath: '/dons'
      preLoaderRoute: typeof DonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof ProjetsRoute
    }
    '/mediatheque/videos': {
      id: '/mediatheque/videos'
      path: '/videos'
      fullPath: '/mediatheque/videos'
      preLoaderRoute: typeof MediathequeVideosRouteImport
      parentRoute: typeof MediathequeRoute
    }
    '/annuaire/organisations': {
      id: '/annuaire/organisations'
      path: '/annuaire/organisations'
      fullPath: '/annuaire/organisations'
      preLoaderRoute: typeof AnnuaireOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/ecoles-specialisees': {
      id: '/annuaire/ecoles-specialisees'
      path: '/annuaire/ecoles-specialisees'
      fullPath: '/annuaire/ecoles-specialisees'
      preLoaderRoute: typeof AnnuaireEcolesSpecialiseesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/ecoles-inclusives': {
      id: '/annuaire/ecoles-inclusives'
      path: '/annuaire/ecoles-inclusives'
      fullPath: '/annuaire/ecoles-inclusives'
      preLoaderRoute: typeof AnnuaireEcolesInclusivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
  }
}

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

interface MediathequeRouteChildren {
  MediathequeVideosRoute: typeof MediathequeVideosRoute
}

const MediathequeRouteChildren: MediathequeRouteChildren = {
  MediathequeVideosRoute: MediathequeVideosRoute,
}

const MediathequeRouteWithChildren = MediathequeRoute._addFileChildren(
  MediathequeRouteChildren,
)

interface ProjetsRouteChildren {
  ProjetsSlugRoute: typeof ProjetsSlugRoute
}

const ProjetsRouteChildren: ProjetsRouteChildren = {
  ProjetsSlugRoute: ProjetsSlugRoute,
}

const ProjetsRouteWithChildren =
  ProjetsRoute._addFileChildren(ProjetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRouteWithChildren,
  AdminRoute: AdminRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DonsRoute: DonsRoute,
  HistoriqueRoute: HistoriqueRoute,
  MediathequeRoute: MediathequeRouteWithChildren,
  PartenairesRoute: PartenairesRoute,
  ProjetsRoute: ProjetsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnnuaireEcolesInclusivesRoute: AnnuaireEcolesInclusivesRoute,
  AnnuaireEcolesSpecialiseesRoute: AnnuaireEcolesSpecialiseesRoute,
  AnnuaireOrganisationsRoute: AnnuaireOrganisationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
